### ISSUE TITLE
Support dependencies

### ISSUE THREAD

**Issue by dsully** [containerbuildsystem/pyarn#11]
Hi - would you be open to a PR to support capturing dependencies as part of a Package?

Also, I'd like to add type hints.

Thanks!

**Comment by dsully** [comment]
Created #12

**Comment by chmeliik** [comment]
Thank you! Released in https://pypi.org/project/pyarn/0.1.2/.

I would be open to adding type hints as well, feel free to add them if you want.

**Comment by lcarva** [comment]
@chmeliik, @dsully is this issue resolved?
